spring:
  application:
    name: cn-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/srinivasa-vasu/spring-boot-services-config
management:
  endpoints:
    web:
      exposure:
        include: '*'
