spring:
  cloud:
    cloudfoundry:
      discovery:
        use-dns: true
        use-container-ip: true
serviceId:
  city: cn-city-service
  weather: cn-weather-service

ribbon:
  cloudfoundry:
    enabled: false
#  eager-load:
#    enabled: true
#    clients: cn-city-service,cn-weather-service