---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cn-egateway-service
  labels:
    type: inject
    mod: fast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cn-egateway-service
  minReadySeconds: 50
  template:
    metadata:
      labels:
        app: cn-egateway-service
#      annotations:
#        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: spring
      containers:
        - name: app-service
          image: humourmind/cn-egateway-service
          imagePullPolicy: Always
